[workspace]
members = [
    "crates/iriscope-app",
    "crates/iriscope-camera-linux",
    "crates/iriscope-camera-macos",
    "crates/iriscope-camera-windows",
    "crates/iriscope-core",
    "crates/iriscope-imaging",
    "crates/iriscope-renderer",
]
default-members = ["crates/iriscope-app"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.89"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
